### ISSUE TITLE
Crashes on Ubuntu 10.04

### ISSUE THREAD

**Issue by bk138** [92bondstreet/initd-forever#7]
Hi there, on Ubuntu 10.04 with node 0.10.33 I get

```
$ initd-forever 

fs.js:429
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:429:11)
    at Object.fs.writeFile (fs.js:953:6)
    at Object.Daemon.writeFiles (/usr/lib/node_modules/initd-forever/lib/main.js:267:10)
    at Object.Daemon.script (/usr/lib/node_modules/initd-forever/lib/main.js:190:13)
    at Object.<anonymous> (/usr/lib/node_modules/initd-forever/bin/initd-forever.js:20:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Any idea?

**Comment by MoemenMostafa** [comment]
same issue on Debian 7.7 node v0.10.18

**Comment by MoemenMostafa** [comment]
I had found the problem after reviewing the code we should specify the -n parameter as follows:

~~~
initd-forever -a <your_app.js> -n <daemon-name>
~~~

**Comment by 92bondstreet** [comment]
Thanks for your investigation. It's weird because I use default value for missing arguments as -a, -n ... etc...

**Comment by MoemenMostafa** [comment]
I will try to debug it when I have time.
